server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/matjip?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL8Dialect #사용할 DB 종류와 버전

  jpa:
    hibernate:
      ddl-auto: update             # 개발에서는 테이블 자동 업데이트
    properties:
      hibernate:
        show_sql: true             # SQL 콘솔 출력
        format_sql: true           # 보기 좋게 포맷
    defer-datasource-initialization: true

  sql:
    init:
      mode: always                 # schema.sql / data.sql 항상 실행

  devtools:
    restart:
      enabled: true                # 코드 변경 시 자동 재시작
    livereload:
      enabled: true                # 브라우저 자동 새로고침

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
